#!/usr/bin/env bash
# Chaos fork reproduction for the CURRENT live guard (docs/chaos-report.md section 2).
#
# Starts anvil against a Sepolia fork, then exercises the live guard
# (0x94FB7677358c44BB0617029a3162108Ae3aa557a, executor 0x1776d4d751d97c85845bf54e6ce364cec62d4bbf)
# with the position contract 0xE1Ee5dB5Cf1f07ef9e1E361A09d5d9A6BEBe8FeE.
# Calldata is generated by scripts/gen-chaos-calldata.py (cast cannot parse nested
# tuple arrays). Requires: anvil, cast, python3.
set -euo pipefail

RPC="${RPC:-http://127.0.0.1:8551}"
EXECUTOR=0x1776d4d751d97c85845bf54e6ce364cec62d4bbf
GUARD=0x94FB7677358c44BB0617029a3162108Ae3aa557a
POOL=0xE1Ee5dB5Cf1f07ef9e1E361A09d5d9A6BEBe8FeE
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if ! curl -s -X POST "$RPC" -H 'content-type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' >/dev/null 2>&1; then
  echo "starting anvil fork on $RPC"
  anvil --fork-url https://ethereum-sepolia-rpc.publicnode.com --port 8551 >/tmp/anvil-fork.log 2>&1 &
  ANVIL_PID=$!
  for _ in $(seq 1 30); do
    curl -s -X POST "$RPC" -H 'content-type: application/json' -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' >/dev/null 2>&1 && break
    sleep 1
  done
else
  ANVIL_PID=""
fi

CAL=$("$ROOT/scripts/gen-chaos-calldata.py" "$POOL" "$GUARD")
SAFE=$(echo "$CAL" | head -1)
UNSAFE=$(echo "$CAL" | tail -1)

echo "== 1. safe repay (the keeper's own rebalance; live-mined on mainnet as 0x830860d0…) =="
cast call --rpc-url "$RPC" --from "$EXECUTOR" "$GUARD" "$SAFE" 2>&1 | head -c 80 || true
echo
echo "== 2. unsafe borrow 50 ETH (HF → 0.719 < floor) — expect revert =="
cast call --rpc-url "$RPC" --from "$EXECUTOR" "$GUARD" "$UNSAFE" 2>&1 | head -c 120 || true
echo
echo "== 3. non-executor — expect NOYEET/1:NOT_EXECUTOR =="
cast call --rpc-url "$RPC" --from 0x0000000000000000000000000000000000000BAD "$GUARD" "$SAFE" 2>&1 | head -c 110 || true
echo
echo "== 4. position state (unchanged — nothing above was mined) =="
cast call --rpc-url "$RPC" "$POOL" "getUserAccountData(address)(uint256,uint256,uint256,uint256,uint256,uint256)" "$GUARD"

if [ -n "$ANVIL_PID" ]; then kill "$ANVIL_PID" 2>/dev/null || true; fi
